# See http://www.fig.sh/ for how this works.
#
# Environment variables that have no value below
# must be set before running fig, see README.md.

# Single etcd server for now
# Example set/get from any host which can access HOST_IP:
#   curl -s -L http://$HOST_IP:4001/v2/stats/leader
#   curl -XPUT -d value="This is foo at $(date)" http://$HOST_IP:4001/v2/keys/tmp/test
#   curl http://$HOST_IP:4001/v2/keys/tmp/test
etcd:
  build: etcd
  environment:
    HOST_IP:
    ETCD_PORT: "4001"
    PEER_PORT: "7001"
  ports:
  - "4001:4001"
  - "7001:7001"

# HAproxy with dynamic backends driven by confd
# HTTP backends can be added as follows (example from the host mac)
#   curl -XPUT -d value="www.perdu.com:80" http://$HOST_IP:4001/v2/keys/http/backends/perdu
# where "perdu" at the end of the URL must be a unique ID.
# Remove those URLs with an HTTP DELETE. 
haproxy:
  build: haproxy
  environment:
    HOST_IP:
    CONFD_INTERVAL: "2"
  links:
    - etcd:etcd
  ports:
  - "80:80"
  - "81:81"

mongo:
  image: "mongo:2.6"
  entrypoint: /usr/local/bin/mongod
  # TODO getting "Insufficient free space for journal files" sometimes
  command: --nojournal
  ports:
  - "27017"
  
sling:
  build: sling
  ports:
  - "80"
  links:
    - mongo:mongo
    - etcd:etcd  
    - graphite:graphite

graphite:
  image: "nickstenning/graphite"
  ports:
  - "82:80"
  - "2003:2003/udp"
  - "2003:2003/tcp"
  - "2004:2004"

